### ISSUE TITLE
Functionality - Organization Settings

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#17]
FUNCTIONALITY:
-
* SAVE
* DELETE
* CANCEL
* Make Organization a Private org.

Reference from local:
-
![image](https://cloud.githubusercontent.com/assets/10201846/8301542/302a09bc-19c1-11e5-8291-4f6ffd3a175c.png)

**Comment by chrisperez** [comment]
ISSUE-017 Organization Settings is updated.

- Latest UI
- Now able to delete organization records. Still need to add warning message before deletion continues.
- Now able to update/change organization's detail except the checkbox "Private Profile"

**Comment by chrisperez** [comment]
- Cancel button from the setting page was removed
- Cancel Button and Private Profile checkbox from the create organization page was removed

**Comment by gigiadamantopoulos** [comment]
No problem found... but should add this:

![image](https://cloud.githubusercontent.com/assets/10202106/8416447/6f0ed312-1ed8-11e5-8d67-4a2d42071e1c.png)

**Comment by Jinsuke** [comment]
Organization Settings Update
--
- Members on the Organization won't be removed even after deleting the Organization. Member data will remain on the Database.

![image](https://cloud.githubusercontent.com/assets/10201846/8448652/7ffd5732-1ffc-11e5-952c-fc1c048686d6.png)

**Comment by gigiadamantopoulos** [comment]
Member data will be in the database, but will they be still included in the member list? Since the organization will be deleted, this will not exist anymore, correct? 

Will you still register an employee if, for example, you have already deleted the organization and decided to create a new one and add that same employee?

![image](https://cloud.githubusercontent.com/assets/10202106/8462358/efbd1490-2065-11e5-9add-ed8035f4ac70.png)

**Comment by Jinsuke** [comment]
[TBD]

**Comment by asjr4584** [comment]
Please re-assign this back to Gigi once this issue is ready for QA again.

**Comment by asjr4584** [comment]
@Jinsuke please explain here what we discussed regarding the org deletion. Then assign back to @gigiadamantopoulos

**Comment by Jinsuke** [comment]
Updates
-
- If an Organization has been deleted, Members will not be deleted, only deactivated. Members will now become an employee account without an organization
- An employee account without an organization can still be searched and assigned to an organization to be active again.

**Comment by gigiadamantopoulos** [comment]
Noted. Thanks!

**Comment by lyn2711** [comment]
Under Organizations tab at the top, click on Create Organization, then it will show Organization Settings.  Can we change that to Create Organization also since that's the only function of it?

And if I clicked on, for example, Corel Org, can we change the word "Settings" on the left side to "Update/Delete"?


![image](https://cloud.githubusercontent.com/assets/7370325/8800666/4291a7cc-2fe7-11e5-9b7d-dedea6de1405.png)

**Comment by Jinsuke** [comment]
:new: Update
-
- Settings page is now moved to the name of the Organization as a clickable link.
![image](https://cloud.githubusercontent.com/assets/10201846/8819910/286455ec-3083-11e5-9151-61f8247cb362.png)

- "Organization Settings" text under /organization/create is now "CREATE ORGANIZATION"
![image](https://cloud.githubusercontent.com/assets/10201846/8819921/53574a0c-3083-11e5-9537-d4c752c932bd.png)

**Comment by lyn2711** [comment]
Even if there is a disclaimer at the top of the Delete button, can we still add a message "Are you sure you want to delete "Name of Organization" once "Delete" is clicked?

**Comment by alvincrisuycorel** [comment]
Reference #41 

Done Merging. Please check :smile:

**Comment by gigiadamantopoulos** [comment]
Passed.

**Comment by lyn2711** [comment]
Passed, done in 203

**Comment by gigiadamantopoulos** [comment]
passed in 201
