### ISSUE TITLE
Functionality - Create Organization

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#7]
User Interface for Creating Organizations. 
-
**USER INTERFACE**
- Organization ID
- Organization Name
- CREATE button
- CANCEL button

**FUNCTIONALITY**
- CREATE
- CANCEL

**Reference Mockup**
![image](https://cloud.githubusercontent.com/assets/10201846/8296037/d77aa54e-197d-11e5-8d38-bc6ac8de3b89.png)

**Comment by chrisperez** [comment]
Done in my Local and changes are pushed to Git.

**Comment by chrisperez** [comment]
- Cancel Button and Private Profile checkbox from the create organization page was removed

**Comment by gigiadamantopoulos** [comment]
No issues here

**Comment by Jinsuke** [comment]
150630 UI UPDATE

![image](https://cloud.githubusercontent.com/assets/10201846/8421861/7f4789c6-1f06-11e5-8cfa-75fe5b9a9a02.png)

**Comment by gigiadamantopoulos** [comment]
Hi All,

Tried creating an organization by only adding an organization name and it saved.

Issue: Organization ID should be automated and cannot be edited when creating an organization.

![image](https://cloud.githubusercontent.com/assets/10202106/8459694/9042e594-2051-11e5-8c9f-577b7f8cf172.png)

**Comment by asjr4584** [comment]
@alvincrisuycorel assigning this back to you for a comment.

**Comment by chrisperez** [comment]
@gigiadamantopoulos,

Added field validation. Please test.

**Comment by gigiadamantopoulos** [comment]
Passed

**Comment by alvincrisuycorel** [comment]
The organization id will be used in the future. I put it there so that the user can choose his/her organization id not generated by the system. It will be more difficult if the system will create an ID base on the organization name. 

Though this feature is still not used in our system but in some case if the system goes larger the organization id will be use for addressing urls. Example usage

The admin/manager can switch different organization by just typing

http://16.178.42.203/corel/dashboard
http://16.178.42.203/guthyrenker/dashboard

not http://16.178.42.203/organization/dashboard (current implementation)

**Comment by asjr4584** [comment]
@alvincrisuycorel should we create a new GitHub issue for the organization ID enhancement and put it on hold until further notice? So that the focus of this issue is the functionality of the Organization. Please advise.

**Comment by alvincrisuycorel** [comment]
Hi sir we can create a new issue for this enhancement. It can be included in Milestone 3.

The current functions are working in creating an organization.

**Comment by asjr4584** [comment]
Thanks @alvincrisuycorel 

Hi @gigiadamantopoulos can you create a new GitHub issue for this enhancement and tag it to Milestone 3, please?

**Comment by gigiadamantopoulos** [comment]
Github issue now created. Refer to https://github.com/HP-Corel/AttendanceTracker/issues/37

**Comment by lyn2711** [comment]
Pass

**Comment by lyn2711** [comment]
Pass, test done on QA server

**Comment by gigiadamantopoulos** [comment]
Passed in 201
